import ANNOTATION from 'raw!./annotation_24px.svg';
import ANNOTATION_HIGHLIGHT_COMMENT from 'raw!./annotation_highlight_comment_24px.svg';
import DROP_DOWN from 'raw!./arrow_drop_down_24px.svg';
import DROP_UP from 'raw!./arrow_drop_up_24px.svg';
import DELETE from 'raw!./delete_24px.svg';
import FULLSCREEN_IN from 'raw!./full_screen_in_24px.svg';
import FULLSCREEN_OUT from 'raw!./full_screen_out_24px.svg';
import HIGHLIGHT from 'raw!./highlight_24px.svg';
import ROTATE_LEFT from 'raw!./rotate_left_24px.svg';
import ZOOM_IN from 'raw!./zoom_in_24px.svg';
import ZOOM_OUT from 'raw!./zoom_out_24px.svg';
import ARROW_LEFT from 'raw!./arrow_left_24px.svg';
import ARROW_RIGHT from 'raw!./arrow_right_24px.svg';
import CHECK_MARK from 'raw!./checkmark_24px.svg';
import GEAR from 'raw!./gear_24px.svg';
import FILE_DEFAULT from 'raw!./file_default.svg';
import FILE_ZIP from 'raw!./file_zip.svg';
import FILE_MEDIA from 'raw!./file_media.svg';
import VR from 'raw!./3D_vr_24px.svg';
import RESET from 'raw!./3D_reset_24px.svg';
import FIND_DROP_DOWN from 'raw!./arrow_drop_down.svg';
import FIND_DROP_UP from 'raw!./arrow_drop_up.svg';
import CLOSE from 'raw!./close.svg';
import SEARCH from 'raw!./search.svg';

export const ICON_ANNOTATION = ANNOTATION;
export const ICON_ANNOTATION_HIGHLIGHT_COMMENT = ANNOTATION_HIGHLIGHT_COMMENT;
export const ICON_DROP_DOWN = DROP_DOWN;
export const ICON_DROP_UP = DROP_UP;
export const ICON_DELETE = DELETE;
export const ICON_FULLSCREEN_IN = FULLSCREEN_IN;
export const ICON_FULLSCREEN_OUT = FULLSCREEN_OUT;
export const ICON_HIGHLIGHT = HIGHLIGHT;
export const ICON_ROTATE_LEFT = ROTATE_LEFT;
export const ICON_ZOOM_IN = ZOOM_IN;
export const ICON_ZOOM_OUT = ZOOM_OUT;
export const ICON_ARROW_LEFT = ARROW_LEFT;
export const ICON_ARROW_RIGHT = ARROW_RIGHT;
export const ICON_CHECK_MARK = CHECK_MARK;
export const ICON_GEAR = GEAR;
export const ICON_FILE_DEFAULT = FILE_DEFAULT;
export const ICON_FILE_ZIP = FILE_ZIP;
export const ICON_FILE_MEDIA = FILE_MEDIA;
export const ICON_3D_VR = VR;
export const ICON_3D_RESET = RESET;
export const ICON_FIND_DROP_DOWN = FIND_DROP_DOWN;
export const ICON_FIND_DROP_UP = FIND_DROP_UP;
export const ICON_CLOSE = CLOSE;
export const ICON_SEARCH = SEARCH;
