queue_rules:
    - name: default
      conditions:
        - status-success=Travis CI - Pull Request

pull_request_rules:
  - name: Automatic strict merge
    conditions:
      - base=master
      - "#approved-reviews-by>=1"
      - "#changes-requested-reviews-by=0"
      - "#review-requested=0"
      - status-success=Travis CI - Pull Request
      - label=ready-to-merge
      - label!=do-not-merge
      - title~=^(build|ci|chore|docs|feat|fix|perf|refactor|revert|style|test)(\([^)]+\))?:\s.+$
    actions:
      queue:
        method: squash
        name: default
