import React from 'react';
import classNames from 'classnames';
import { Props as DurationLabelsProps } from '../controls/media/DurationLabels';
import HDBadge from '../controls/media/HDBadge';
import MediaFullscreenToggle, { Props as MediaFullscreenToggleProps } from '../controls/media/MediaFullscreenToggle';
import MediaSettings, { Props as MediaSettingsProps } from '../controls/media/MediaSettings';
import PlayPauseToggle, { Props as PlayControlsProps } from '../controls/media/PlayPauseToggle';
import SubtitlesToggle, { Props as SubtitlesToggleProps } from '../controls/media/SubtitlesToggle';
import TimeControls, { Props as TimeControlsProps } from '../controls/media/TimeControls';
import VolumeControls, { Props as VolumeControlsProps } from '../controls/media/VolumeControls';
import { SUBTITLES_OFF } from '../../constants';
import './DashControls.scss';
import AnnotationsControls from '../controls/annotations/AnnotationsControls';
import { AnnotationMode } from '../../types/annotations';

export type Props = DurationLabelsProps &
    MediaFullscreenToggleProps &
    MediaSettingsProps &
    PlayControlsProps &
    SubtitlesToggleProps &
    TimeControlsProps &
    VolumeControlsProps & {
        isPlayingHD?: boolean;
        moveVideoPlayback: (forward: boolean, duration: number) => void;
        v2?: boolean;
        annotationColor?: string;
        annotationMode?: AnnotationMode;
        onAnnotationModeClick?: ({ mode }: { mode: AnnotationMode }) => void;
        onAnnotationModeEscape?: () => void;
    };

export default function DashControls({
    audioTrack,
    audioTracks,
    autoplay,
    aspectRatio,
    bufferedRange,
    currentTime,
    durationTime,
    filmstripInterval,
    filmstripUrl,
    isAutoGeneratedSubtitles,
    isHDSupported,
    isPlaying,
    isPlayingHD,
    onAudioTrackChange,
    onAutoplayChange,
    onFullscreenToggle,
    onMuteChange,
    onPlayPause,
    onQualityChange,
    onRateChange,
    onSubtitleChange,
    onSubtitlesToggle,
    onTimeChange,
    onVolumeChange,
    moveVideoPlayback,
    quality,
    rate,
    subtitle,
    subtitles = [],
    volume,
    v2,
    annotationColor,
    annotationMode,
    onAnnotationModeClick,
    onAnnotationModeEscape,
}: Props): JSX.Element {
    const hasRegion = true;
    return (
        <div
            className={classNames('bp-DashControls', {
                v2,
            })}
            data-testid="media-controls-wrapper"
        >
            <TimeControls
                aspectRatio={aspectRatio}
                bufferedRange={bufferedRange}
                currentTime={currentTime}
                durationTime={durationTime}
                filmstripInterval={filmstripInterval}
                filmstripUrl={filmstripUrl}
                onTimeChange={onTimeChange}
            />

            <div className="bp-DashControls-bar">
                <div className="bp-AnnotationsControls-group">
                    <AnnotationsControls
                        annotationColor={annotationColor}
                        annotationMode={annotationMode}
                        hasDrawing
                        hasRegion
                        onAnnotationModeClick={onAnnotationModeClick}
                        onAnnotationModeEscape={onAnnotationModeEscape}
                    />
                </div>
                <div className="bp-DashControls-group">
                    <PlayPauseToggle
                        isPlaying={isPlaying}
                        moveVideoPlayback={moveVideoPlayback}
                        onPlayPause={onPlayPause}
                    />
                </div>

                <div className="bp-DashControls-group">
                    <VolumeControls
                        onMuteChange={onMuteChange}
                        onVolumeChange={onVolumeChange}
                        v2={v2}
                        volume={volume}
                    />
                    <SubtitlesToggle
                        isAutoGeneratedSubtitles={isAutoGeneratedSubtitles}
                        isShowingSubtitles={subtitle !== SUBTITLES_OFF}
                        onSubtitlesToggle={onSubtitlesToggle}
                        subtitles={subtitles}
                    />
                    <MediaSettings
                        audioTrack={audioTrack}
                        audioTracks={audioTracks}
                        autoplay={autoplay}
                        badge={isPlayingHD ? <HDBadge /> : undefined}
                        className="bp-DashControls-settings v2"
                        isHDSupported={isHDSupported}
                        onAudioTrackChange={onAudioTrackChange}
                        onAutoplayChange={onAutoplayChange}
                        onQualityChange={onQualityChange}
                        onRateChange={onRateChange}
                        onSubtitleChange={onSubtitleChange}
                        quality={quality}
                        rate={rate}
                        subtitle={subtitle}
                        subtitles={subtitles}
                        v2
                    />
                    <MediaFullscreenToggle onFullscreenToggle={onFullscreenToggle} />
                </div>
            </div>
        </div>
    );
}
