import React from 'react';
import { Props as DurationLabelsProps, formatTime } from '../controls/media/DurationLabels';

import MediaSettings, { Props as MediaSettingsProps } from '../controls/media/MediaSettings';
import MediaToggle from '../controls/media/MediaToggle';
import SubtitlesToggle, { Props as SubtitlesToggleProps } from '../controls/media/SubtitlesToggle';
import TimeControlsV2, { Props as TimeControlsProps } from '../controls/media/TimeControlsV2';
import VolumeControls, { Props as VolumeControlsProps } from '../controls/media/VolumeControls';
import IconPlay24 from '../controls/icons/IconPlay24';
import IconPause24 from '../controls/icons/IconPause24';
import { SUBTITLES_OFF } from '../../constants';
import { AnnotationMode } from '../../types/annotations';
import AnnotationsControls from '../controls/annotations/AnnotationsControls';
import DrawingControls from '../controls/annotations/DrawingControls';
import './VideoControlsV2.scss';

export type Props = DurationLabelsProps &
    MediaSettingsProps &
    SubtitlesToggleProps &
    TimeControlsProps &
    VolumeControlsProps & {
        fps?: number;
        annotationColor?: string;
        annotationMode?: AnnotationMode;
        hasDrawing?: boolean;
        hasRegion?: boolean;
        isPlaying?: boolean;
        isNarrowVideo?: boolean;
        onAnnotationModeClick: ({ mode }: { mode: AnnotationMode }) => void;
        onAnnotationModeEscape: () => void;
        onAnnotationColorChange: (color: string) => void | undefined;
        onPlayPause: (isPlaying: boolean) => void;
        videoAnnotationsEnabled?: boolean;
    };

export default function VideoControlsV2({
    aspectRatio,
    audioTrack,
    audioTracks,
    autoplay,
    bufferedRange,
    currentTime = 0,
    durationTime = 0,
    filmstripInterval,
    filmstripUrl,
    fps,
    mediaEl,
    hasDrawing,
    hasRegion,
    isAutoGeneratedSubtitles,
    isHDSupported,
    isPlaying,
    isNarrowVideo,
    onAudioTrackChange,
    onAutoplayChange,
    onMuteChange,
    onPlayPause,
    onQualityChange,
    onRateChange,
    onSubtitleChange,
    onSubtitlesToggle,
    onTimeChange,
    onVolumeChange,
    quality,
    rate,
    subtitle,
    subtitles = [],
    volume,
    annotationColor,
    annotationMode,
    onAnnotationModeClick,
    onAnnotationModeEscape,
    videoAnnotationsEnabled = false,
    onAnnotationColorChange,
}: Props): JSX.Element {
    const PlayPauseIcon = isPlaying ? IconPause24 : IconPlay24;
    const playPauseTitle = isPlaying ? __('media_pause') : __('media_play');

    const timeLabel = isNarrowVideo
        ? formatTime(currentTime)
        : `${formatTime(currentTime)} / ${formatTime(durationTime)}`;

    return (
        <div className="bp-VideoControlsV2" data-testid="media-controls-wrapper-v2">
            <TimeControlsV2
                aspectRatio={aspectRatio}
                bufferedRange={bufferedRange}
                currentTime={currentTime}
                durationTime={durationTime}
                filmstripInterval={filmstripInterval}
                filmstripUrl={filmstripUrl}
                fps={fps}
                mediaEl={mediaEl}
                onTimeChange={onTimeChange}
            />
            <div className="bp-VideoControlsV2-bar">
                <div className="bp-VideoControlsV2-group bp-VideoControlsV2-group--left">
                    <MediaToggle
                        className="bp-VideoControlsV2-playPause"
                        data-resin-target="playPause"
                        onClick={() => onPlayPause(!isPlaying)}
                        title={playPauseTitle}
                    >
                        <PlayPauseIcon />
                    </MediaToggle>
                    <span className="bp-VideoControlsV2-timestamp" data-testid="bp-VideoControlsV2-timestamp">
                        {timeLabel}
                    </span>
                </div>
                <div className="bp-VideoControlsV2-group bp-VideoControlsV2-group--right">
                    <VolumeControls onMuteChange={onMuteChange} onVolumeChange={onVolumeChange} volume={volume} />
                    <SubtitlesToggle
                        isAutoGeneratedSubtitles={isAutoGeneratedSubtitles}
                        isShowingSubtitles={subtitle !== SUBTITLES_OFF}
                        onSubtitlesToggle={onSubtitlesToggle}
                        subtitles={subtitles}
                    />
                    <MediaSettings
                        audioTrack={audioTrack}
                        audioTracks={audioTracks}
                        autoplay={autoplay}
                        className="bp-VideoControls-settings"
                        isHDSupported={isHDSupported}
                        onAudioTrackChange={onAudioTrackChange}
                        onAutoplayChange={onAutoplayChange}
                        onQualityChange={onQualityChange}
                        onRateChange={onRateChange}
                        onSubtitleChange={onSubtitleChange}
                        quality={quality}
                        rate={rate}
                        subtitle={subtitle}
                        subtitles={subtitles}
                    />
                    {videoAnnotationsEnabled && (
                        <>
                            <AnnotationsControls
                                annotationColor={annotationColor}
                                annotationMode={annotationMode}
                                hasDrawing={hasDrawing}
                                hasRegion={hasRegion}
                                isVideo
                                onAnnotationModeClick={onAnnotationModeClick}
                                onAnnotationModeEscape={onAnnotationModeEscape}
                            />
                            <DrawingControls
                                annotationColor={annotationColor}
                                annotationMode={annotationMode}
                                onAnnotationColorChange={onAnnotationColorChange}
                            />
                        </>
                    )}
                </div>
            </div>
        </div>
    );
}
